; font="LXGW WenKai"
font="FiraCode Nerd Font Mono:size=14, LXGW Wenkai Mono:size=14"
use-bold=yes
lines=10
line-height=25
width=40

[colors]
background=24273add
text=cad3f5ff
prompt=b8c0e0ff
placeholder=8087a2ff
input=cad3f5ff
match=8aadf4ff
selection=5b6078ff
selection-text=cad3f5ff
selection-match=8aadf4ff
counter=8087a2ff
border=8aadf4ff


[border]
width=2
radius=10
selection-radius=10
