[colors.primary]
background = '#000000'
foreground = '#e3e2e4'

[colors.cursor]
text = '#000000'
cursor = '#e3e2e4'

[colors.vi_mode_cursor]
text = '#000000'
cursor = '#accae7'

[colors.search.matches]
foreground = '#353a40'
background = '#dcbce1'

[colors.search.focused_match]
foreground = '#353a40'
background = '#accae7'

[colors.footer_bar]
foreground = '#353a40'
background = '#e3e2e4'

[colors.hints.start]
foreground = '#353a40'
background = '#bdc8d4'

[colors.hints.end]
foreground = '#353a40'
background = '#bdc8d4'

[colors.selection]
text = '#c3c7cd'
background = '#42474d'


[colors.normal]
black   = '#42474d'
red     = '#ffb4ab'
green   = '#accae7'
yellow  = '#bdc8d4'
blue    = '#dcbce1'
magenta = '#accae7'
cyan    = '#bdc8d4'
white   = '#e3e2e4'


[colors.bright]
black   = '#8d9197'
red     = '#ffb4ab'
green   = '#accae7'
yellow  = '#bdc8d4'
blue    = '#dcbce1'
magenta = '#accae7'
cyan    = '#bdc8d4'
white   = '#e3e2e4'


[colors.dim]
black   = '#42474d'
red     = '#ffb4ab'
green   = '#accae7'
yellow  = '#bdc8d4'
blue    = '#dcbce1'
magenta = '#accae7'
cyan    = '#bdc8d4'
white   = '#e3e2e4'
