[window]
padding = { x = 0, y = 0 }
dynamic_padding = true
opacity = 0.9
blur = true

[font]
size = 12
normal = { family = "JetBrains Mono", style = "Regular" }
bold = { family = "JetBrains Mono", style = "Bold" }
italic = { family = "JetBrains Mono", style = "Italic" }
bold_italic = { family = "JetBrains Mono", style = "Bold Italic" }

[colors.primary]
background = "#161616"
foreground = "#e4e4e4"
dim_foreground = "#a0a0a0"
bright_foreground = "#f6f6f6"

[colors.cursor]
text = "#161616"
cursor = "#f2f2f2"

[colors.vi_mode_cursor]
text = "#161616"
cursor = "#d6d6d6"

[colors.search.matches]
foreground = "#161616"
background = "#a0a0a0"

[colors.search.focused_match]
foreground = "#161616"
background = "#f2f2f2"

[colors.footer_bar]
foreground = "#161616"
background = "#a0a0a0"

[colors.hints.start]
foreground = "#161616"
background = "#d6d6d6"

[colors.hints.end]
foreground = "#161616"
background = "#8c8c8c"

[colors.selection]
text = "#161616"
background = "#d6d6d6"

[colors.normal]
black = "#2a2a2a"
red = "#c47f7f"
green = "#91ad98"
yellow = "#b6a678"
blue = "#8faac1"
magenta = "#aa8dab"
cyan = "#84aaa8"
white = "#dedede"

[colors.bright]
black = "#555555"
red = "#dc9696"
green = "#a8c2ad"
yellow = "#ccbc8d"
blue = "#a8bfd2"
magenta = "#c0a5c1"
cyan = "#9fc3c1"
white = "#f6f6f6"

[[colors.indexed_colors]]
index = 16
color = "#c89478"

[[colors.indexed_colors]]
index = 17
color = "#d8b1b1"

[cursor]
thickness = 0.1

[cursor.style]
shape = "Beam"
blinking = "on"

[terminal.shell]
program = "/bin/zsh"
