[window]
padding = { x = 0, y = 0 }
dynamic_padding = true
opacity = 0.9
blur = true

[font]
size = 12
normal = { family = "JetBrains Mono", style = "Regular" }
bold = { family = "JetBrains Mono", style = "Bold" }
italic = { family = "JetBrains Mono", style = "Italic" }
bold_italic = { family = "JetBrains Mono", style = "Bold Italic" }

[colors.primary]
background = "#202020"
foreground = "#e8e8e8"
dim_foreground = "#a8a8a8"
bright_foreground = "#fafafa"

[colors.cursor]
text = "#202020"
cursor = "#f2f2f2"

[colors.vi_mode_cursor]
text = "#202020"
cursor = "#d6d6d6"

[colors.search.matches]
foreground = "#202020"
background = "#a0a0a0"

[colors.search.focused_match]
foreground = "#202020"
background = "#f2f2f2"

[colors.footer_bar]
foreground = "#202020"
background = "#a0a0a0"

[colors.hints.start]
foreground = "#202020"
background = "#d6d6d6"

[colors.hints.end]
foreground = "#202020"
background = "#8c8c8c"

[colors.selection]
text = "#202020"
background = "#d6d6d6"

[colors.normal]
black = "#363636"
red = "#d18b8b"
green = "#9ebaa5"
yellow = "#c2b486"
blue = "#9bb7cf"
magenta = "#b59ab6"
cyan = "#91b8b6"
white = "#e6e6e6"

[colors.bright]
black = "#666666"
red = "#e2a0a0"
green = "#b2cbb7"
yellow = "#d4c492"
blue = "#b2cbe0"
magenta = "#c9aec9"
cyan = "#abd0ce"
white = "#fafafa"

[[colors.indexed_colors]]
index = 16
color = "#c89478"

[[colors.indexed_colors]]
index = 17
color = "#d8b1b1"

[cursor]
thickness = 0.1

[cursor.style]
shape = "Beam"
blinking = "on"

[terminal.shell]
program = "/bin/zsh"
